version: '2'
services:
    # Web Server Apache
    web:
      build: docker/apache
      ports:
          - ${WEB_PORT}:80
      container_name: web
      image: web
      volumes:
         - ${PROJECTS_PATH}:/var/www/html
         - ./conf/apache/vhosts/:/etc/apache2/sites-enabled/ # Emplacement de VHOST Apache
      env_file:
          - ./.env
      links:
          - php:php
