version: '2.1'
services:
  db:
    image: mongo
    container_name: db    
    env_file: 
      - .env    
    volumes:
      - dbdata_mongodb:/data/db     
  dbadmin:
    image: mongo-express
    container_name: dbadmin

    