# Environnement Web de developpement en PHP 7.0.13 avec Apache
version: '2'
services:
  # Database MySQL
  db:
      restart: always
      image: mysql
      container_name: db
      volumes:
        - ./db/mysql:/var/lib/mysql # Commenter la ligne des volumes pour une base de données non persistente
      environment:
       - MYSQL_ROOT_PASSWORD=root # Mot de passe par defaut pour l'utisateur root

  # To create email during devloppement
  maildev:
      restart: always
      container_name: maildev
      image: djfarrelly/maildev
      container_name: maildev
      ports:
        - "1080:80"

  # PHP Package management
  composer:
    restart: always
    image: composer/composer
    container_name: composer

  # Node / Bower / Grunt
  nodejs-grunt-bower:
    restart: always
    image: digitallyseamless/nodejs-bower-grunt
    container_name: nodejs-bower-grunt

  # PhpMyAdmin
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions
