# Environnement Web de developpement en PHP 7.0.13 avec Apache
version: '2'
services:
  # Database MySQL
  db:
      image: mysql
      container_name: db
      volumes:
        - ./db/mysql:/var/lib/mysql # Commenter la ligne des volumes pour une base de données non persistente
      environment:
       - MYSQL_ROOT_PASSWORD=root # Mot de passe par defaut pour l'utisateur root

  # To create email during devloppement
  maildev:
      container_name: maildev
      image: djfarrelly/maildev
      ports:
        - ${MAILDEV_PORT}:80
        - 1025:25

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    volumes:
      - /sessions

  # Continuous Integration
  ci:
    build: docker/ci
    image: vfalies/ci
    container_name: ci
    depends_on:
      - tools

  # Tools : Composer, Node, Bower, Grunt
  tools:
    build: docker/tools
    image: vfalies/tools
    container_name: tools
