# Web development environment
version: '2.1'
services:
  # To create email during development
  maildev:
      container_name: maildev
      image: djfarrelly/maildev
      ports:
        - ${MAILDEV_PORT}:80
        - 1025:25

  # NodeJS
  nodejs:
    image: node:9.2-alpine
    container_name: node
    volumes:
        - ${PROJECTS_PATH}:/var/www/html
        
  # Web Server
  web:
    extends:
        file: services/${WEB_SERVER}.yml
        service: web
    links:
        - php:php
        - nodejs:nodejs

  # PHP FPM
  php:
    image: vfac/envdevphpbase:${PHP_VERSION}    
    container_name: php
    env_file: 
        - .env
    volumes:
        - ${PROJECTS_PATH}:/var/www/html
        - ./conf/php/php.ini:/usr/local/etc/php/php.ini
    links:
        - db:db
        - maildev:maildev
        - nodejs:nodejs
        - cache:cache

  # Cache server
  cache:
    extends:
        file: services/${CACHE_SERVER}.yml
        service: cache

  # Database
  db:
    extends: 
        file: services/${DB}.yml
        service: db
  
  # Database admin
  dbadmin:
    extends:
        file: services/${DB}.yml
        service: dbadmin
    ports:
        - ${DBADMIN_PORT}:80
    links:
        - db
        
volumes: 
  dbdata_mariadb:
    labels: 
        com.vfac.description: "VFAC EnvDev Database MariaDB volume"
        com.vfac.owner: "VFAC"
        com.vfac.url: "https://vfac.fr"
  dbdata_mysql:
    labels: 
        com.vfac.description: "VFAC EnvDev Database MySQL volume"
        com.vfac.owner: "VFAC"
        com.vfac.url: "https://vfac.fr"        
  dbdata_mongodb:
    labels: 
        com.vfac.description: "VFAC EnvDev Database MongoDB volume"
        com.vfac.owner: "VFAC"
        com.vfac.url: "https://vfac.fr"        