version: '2'
services:
    # Web Server PHP 7 + Apache 2
    web:
      restart: always
      build: docker/php7apache
      container_name: web
      ports:
         - "81:80" # Redirection des portes entre l'hote et Docker
      volumes:
         - ./projects:/var/www/html
         - ./conf/apache/vhosts:/etc/apache2/sites-enabled # Emplacement de VHOST Apache
         - ./conf/php/php.ini:/usr/local/etc/php/conf.d/30-custom.ini # PHP ini custom
      environment:
         - ALLOW_OVERRIDE=true
      links:
         - db:db
         - maildev:maildev
