version: '2'
services:
    # Web Server NGinx
    web:
      image: nginx:alpine
      ports:
          - ${WEB_PORT}:80
      container_name: web
      volumes:
          - ./conf/nginx/vhosts:/etc/nginx/conf.d
          - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ${PROJECTS_PATH}:/var/www/html
      links:
          - php:php
