version: '2.1'
services:
  web:
    image: httpd:2.4-alpine
    ports:
        - ${WEB_PORT}:80
    container_name: web
    volumes:
        - ../${PROJECTS_PATH}:/var/www/html
        - ../conf/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ../conf/apache/vhosts/:/etc/apache2/sites-enabled/