version: '2.1'
services:
  db:
    image: mariadb
    container_name: db    
    env_file: 
      - ../.env    
    volumes:
      - dbdata_mariadb:/var/lib/mysql        
  dbadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dbadmin
